title = '今日无新鲜事'
baseURL = 'https://docura.github.io/'

defaultContentLanguage = 'zh'
languageCode = 'zh-Hans'

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false
theme = 'docura'
