[[main]]
weight = 1
identifier = "docs"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文档"
url = "/docs/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[main]]
weight = 2
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
[[main]]
weight = 3
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""
[[main]]
weight = 4
identifier = "static"
pre = ""
post = ""
url = "https://anapla.beyond.tain.one/finite.tain.one"
name = "访问统计"
title = "访问统计"
[[main]]
identifier = "github"
pre = "<i class='fab fa-github fa-fw'></i>"
post = ""
url = "https://github.com/selcarpa/finite"
title = "GitHub"
weight = 9