description = 'Nothing New Today'

author = 'selcarpa'
authorURL = 'https://github.com/selcarpa'

currentYear = 2023
projectStartYear = 2023


[algolia]
[algolia.en]
container = '#site-header-search'
appId = ''
indexName = ''
apiKey = ''
