enableInlineShortcodes = false

[exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$", '^git$']
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[funcs]
getenv = ["^HUGO_"]

[http]
methods = ["(?i)GET|POST"]
urls = [".*"]