name: build-test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Prepare environments
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.120.4/hugo_0.120.4_linux-amd64.deb && sudo apt install ./hugo*.deb -y

      - name: Build with Hugo
        shell: bash
        run: hugo

      - uses: actions/upload-artifact@v3
        name: Store the build
        with:
          name: public
          path: public/

