name: build-test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-test:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: recursive

      - name: Prepare environments
        run: sudo apt update -y && sudo apt install wget -y && wget https://github.com/gohugoio/hugo/releases/download/v0.121.1/hugo_extended_0.121.1_linux-amd64.deb && sudo apt install ./hugo*.deb -y

      - name: Build with Hugo
        shell: bash
        run: hugo

      - uses: actions/upload-artifact@v3
        name: Store the build
        with:
          name: public
          path: public/

